[mongodb]
mongodb.kodari.online
[catalogue]
catalogue.kodari.online
[redis]
redis.kodari.online
[frontend]
frontend.kodari.online
[user]
user.kodari.online
[cart]
cart.kodari.online
[shipping]
shipping.kodari.online
[mysql]
mysql.kodari.online
[rabbitmq]
rabbitmq.kodari.online
[payment]
payment.kodari.online